services:
  postgres:
    image: postgres:17.5
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

  redis:
    image: redis:alpine
    ports:
      - "6378:${REDIS_PORT}"

  api:
    build: ./api
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
    volumes:
      - ./api:/app

  web:
    build: ./web
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    depends_on:
      - api
    volumes:
      - ./web:/app

volumes:
  pgdata:
